export enum DataModels {
  DB = "db",
  SCHEMA = "schema",
  TABLE = "base table",
  EXTERNAL_TABLE = "external table",
  VIEW = "view",
  MATERIALIZED = "materialized view",
  COLUMN = "column",
  DATASET = "dataset",
  PUBLISHED_DATASOURCE = "published_datasource",
  EMBEDDED_DATASOURCE = "embedded_datasource",
  VISUAL = "sheet",
  DASHBOARD = "dashboard",
  ANALYSIS = "qs_analysis",
  FIELD = "field",
  PROJECT = "project",
  SITE = "site",
  WORKBOOK = "workbook",
  FOLDER = "folder",
  SISENSE_TABLE = "sisense_table",
  SISENSE_FOLDER = "sisense_folder",
  DATA_MODEL = "sisense_datamodel",
  DATAFLOW = "dataflow",
  REPORT = "report",
  SEMANTIC_MODEL = "semantic_model",
  WORKSPACE = "workspace",
  POWER_BI_TABLE = "powerbi_table",
  LOOKER_FOLDERS = "looker_folders",
  LOOKER_BOARD = "looker_board",
  LOOKER_DASHBOARD = "looker_dashboard",
  LOOKER_FOLDER = "looker_folder",
  LOOKER_PROJECTS = "looker_projects",
  LOOKER_PROJECT = "looker_project",
  LOOKER_LOOK = "looker_look",
  LOOKER_BOARDS = "looker_boards",
  LOOKER_DASHBOARDS = "looker_dashboards",
  LOOKER_LOOKS = "looker_looks",
  LOOKER_EXPLORES = "looker_explores",
  LOOKER_VIEWS = "looker_views",
  LOOKER_EXPLORE = "looker_explore",
  LOOKER_VIEW = "looker_view",
  LOOKER_VISUAL = "looker_visual",
}

export enum ConnectionType {
  NEO4J = "neo4j",
  REDSHIFT = "redshift",
  SNOWFLAKE = "snowflake",
  BIG_QUERY = "bigquery",
  DATABRIKS = "databricks",
  TABLEAU = "tableau",
  LOOKER = "looker",
  ATHENA = "athena",
  QUICKSIGHT = "quicksight",
  MYSQL = "mysql",
  MSSQL = "mssql",
  POWER_BI = "powerbi",
  SISENSE = "sisense",
  ORACLE = "oracle",
  VERTICA = "vertica",
  TRINO = "trino",
}

export enum Usage {
  HIGH = "high",
  MEDIUM = "medium",
  LOW = "low",
  UNUSED = "unused",
}
